---
- hosts: "dative-old-local"

  pre_tasks:

    - include_vars: "vars-singlenode.yml"
      tags:
        - "always"

    - name: "Install ack-grep"
      apt:
        pkg: "ack-grep"
        state: "latest"
      become: "yes"

    - name: "Symlink ack-grep to ack"
    - file:
        state: "link"
        src: "/usr/bin/ack-grep"
        dest: "/usr/bin/ack"

    - name: "Install Joel's dotfiles (vim stuff)"
      git:
        repo: "https://github.com/jrwdunham/dotfiles.git"
        dest: "/home/vagrant/downloads"
        version: "master"
        force: "yes"
        accept_hostkey: "yes"

    - name: "Install Joel's dotfiles"
      shell: "./install.sh"
      args:
        chdir: "/home/vagrant/downloads/dotfiles"

  roles:

    - role: "percona"
      become: "yes"
      tags:
        - "percona"

    - role: "old-src"
      become: "yes"
      tags:
        - "old-src"

    - role: "dative-src"
      become: "yes"
      tags:
        - "dative-src"

    - role: "nginx"
      become: "yes"
      tags:
        - "nginx"
